name: STM32CubeIDE Compile Check

# Runs on pushes to pull request
on: pull_request

permissions: {}

jobs:
  cubeide-compile-check:
    name: STM32CubeIDE Compile Check (Debug + Release)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Run Compile Check (Debug + Release)
        uses: xanderhendriks/action-build-stm32cubeide@v15.0
        with:
          project-path: '.'
          project-target: 'cansw_altimeter'
